# 0. Why Numpy?

In [5]:
import time
import numpy as np

In [2]:
N = 1_000_000

py_list = list(range(N))

In [4]:
start = time.perf_counter()
py_result = [x*2+1 for x in py_list]
list_time = time.perf_counter() - start

print(list_time)

0.07359523201012053


In [6]:
np_array = np.arange(N)

start = time.perf_counter()
np_result = np_array*2+1
np_time = time.perf_counter() - start
print(np_time)

0.002825450006639585


# 1.Numpy Fundamentals

In [10]:
scores = np.array([88,54,92,67,45,79,91,63,77,55], dtype=np.int32)

scores

array([88, 54, 92, 67, 45, 79, 91, 63, 77, 55], dtype=int32)

In [11]:
scores.dtype

dtype('int32')

In [12]:
scores.shape

(10,)

In [13]:
scores.ndim

1

In [14]:
scores.size

10

In [16]:
gradebook = np.array(
    [[88, 91, 95],
    [54, 61, 70],
    [92, 95, 98], 
    [67, 72, 65]]
)

In [18]:
gradebook.shape

(4, 3)

In [20]:
gradebook.ndim

2

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [24]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.full(4,999)

array([999, 999, 999, 999])

In [26]:
np.full((2,4),6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6]])

In [27]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

### 🏋️ Exercise — Array Creation

Using **only NumPy constructors** (no Python lists of numbers), create:

1. An array of integers from **1 to 20 inclusive**
2. A **3×3 identity matrix** (float64)
3. A **4×5 matrix** filled with the value `7`
4. A **2×6 matrix** of all zeros with dtype `float32`

Print each array and its `shape` and `dtype`.

In [ ]:
# 1. Integers 1–20
a = np.arange(1, 21)
print(f"1) {a}\n   shape={a.shape}, dtype={a.dtype}\n")

# 2. 3×3 identity matrix
b = np.eye(3)
print(f"2)\n{b}\n   shape={b.shape}, dtype={b.dtype}\n")

# 3. 4×5 matrix of 7s
c = np.full((4, 5), 7)
print(f"3)\n{c}\n   shape={c.shape}, dtype={c.dtype}\n")

# 4. 2×6 zeros float32
e = np.zeros((2, 6), dtype=np.float32)
print(f"5)\n{e}\n   shape={e.shape}, dtype={e.dtype}")

In [ ]:
dtype=np.float32

In [30]:
gradebook

array([[88, 91, 95],
       [54, 61, 70],
       [92, 95, 98],
       [67, 72, 65]])

In [31]:
gradebook.T 

array([[88, 54, 92, 67],
       [91, 61, 95, 72],
       [95, 70, 98, 65]])

In [32]:
scores = np.array([88,54,92,67,45,79,91,63,77,55], dtype=np.int32)

mask = scores > 70
mask

array([ True, False,  True, False, False,  True,  True, False,  True,
       False])

In [35]:
scores[scores<60]

array([54, 45, 55], dtype=int32)

In [36]:
status = np.where(scores>=60, "Pass", "Fail")
status

array(['Pass', 'Fail', 'Pass', 'Pass', 'Fail', 'Pass', 'Pass', 'Pass',
       'Pass', 'Fail'], dtype='<U4')

In [37]:
a = np.array([10,20,30,40,50])
b = np.array([1,2,3,4,5])

print(a+b)
print(a*b)
print(a**b)

[11 22 33 44 55]
[ 10  40  90 160 250]
[       10       400     27000   2560000 312500000]


In [38]:
a + 5 

array([15, 25, 35, 45, 55])

In [39]:
a.mean()

30.0

In [40]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [41]:
np.exp(a)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21])

In [42]:
vals = np.array([1.2, 2.567, 3.89, -4.1])

In [43]:
np.floor(vals)

array([ 1.,  2.,  3., -5.])

In [44]:
np.ceil(vals)

array([ 2.,  3.,  4., -4.])

In [45]:
np.round(vals,1)

array([ 1.2,  2.6,  3.9, -4.1])

In [46]:
flat = np.arange(1,13)
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [47]:
matrix_3_4 = flat.reshape(3,4)
matrix_3_4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
matrix_3_4 = flat.reshape(3,-1)
matrix_3_4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
matrix_3_4.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [52]:
np.random.rand(5)

array([0.27825995, 0.33057064, 0.23030214, 0.77487954, 0.37294523])

In [53]:
np.random.uniform(5,15,6)

array([ 8.65792776, 13.03190007, 10.91722432,  8.23694867, 14.63713435,
        5.64197755])

In [55]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
np.random.choice(arr,4, replace=False)

array([7, 9, 1, 3])

In [59]:
np.random.seed(0)

In [60]:
# estimating pi via simulation

for N in (100, 1000, 10_000, 1_000_000):
    x = np.random.uniform(-1,1,N)
    y = np.random.uniform(-1,1,N)
    
    inside = (x**2 + y**2) <=1
    pi_estimate = 4*inside.sum() / N

    error = abs(pi_estimate -np.pi)
    print(f"Error {error} with {N} samples")


Error 0.05840734641020706 with 100 samples
Error 0.07759265358979306 with 1000 samples
Error 0.036392653589793156 with 10000 samples
Error 0.0003753464102067561 with 1000000 samples
